# Generated by Django 5.2.17 on 2026-09-15 19:08

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PathwayReviewerProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("goal", models.PositiveIntegerField(default=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pathway_review_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PathwayReviewItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "item_id",
                    models.CharField(db_index=True, max_length=16, unique=True),
                ),
                ("family_key", models.CharField(max_length=255)),
                ("pathway", models.CharField(max_length=255)),
                ("careers_covered", models.PositiveIntegerField(default=0)),
                ("mix", models.CharField(blank=True, max_length=16)),
                (
                    "pool",
                    models.CharField(
                        choices=[
                            ("reach", "Reach census"),
                            ("tail", "Stratified tail sample"),
                            ("control", "Seeded control"),
                        ],
                        max_length=16,
                    ),
                ),
                ("stratum", models.CharField(blank=True, max_length=16)),
                ("weight", models.FloatField(default=1.0)),
                ("tier", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("payload", models.JSONField(default=dict)),
                ("control_key", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["tier", "-careers_covered", "item_id"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "tier"],
                        name="pathway_rev_is_acti_448eca_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PathwayReviewVote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("good", "Good"),
                            ("needs_work", "Needs work"),
                            ("bad", "Bad"),
                            ("skip", "Skipped - could not judge"),
                        ],
                        max_length=16,
                    ),
                ),
                ("dropped_steps", models.JSONField(blank=True, default=list)),
                ("replacements", models.JSONField(blank=True, default=dict)),
                ("reasons", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("seconds", models.PositiveIntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="pathway_review.pathwayreviewitem",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pathway_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("item", "reviewer"),
                        name="one_vote_per_reviewer_per_item",
                    )
                ],
            },
        ),
    ]
