# Generated by Django 5.2.17 on 2026-09-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pathway_review", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pathwayreviewvote",
            name="suggestions",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
