coverage:
  status:
    project:
      default:
        enabled: no
        target: auto
    patch:
      default:
        enabled: yes
        target: 100%

comment: false

ignore:
  - "docs/decisions"
