# Docker in this repo is only supported for running tests locally.
services:
  app:
    image: edxops/enterprise-access-dev
    container_name: enterprise-access.test.app
    # Invoke a command that doesn't do anything, as the container is used exclusively for executing tests.
    command: tail -f /dev/null
    volumes:
      - .:/edx/app/enterprise-access/
    stdin_open: true
    tty: true
    environment:
      DJANGO_SETTINGS_MODULE: enterprise_access.settings.test
