.DEFAULT_GOAL := help

.PHONY: help clean piptools requirements ci_requirements dev_requirements \
        validation_requirements doc_requirements production-requirements static shell \
        test coverage isort_check isort style lint quality pii_check validate \
        migrate html_coverage upgrade extract_translation dummy_translations \
        compile_translations fake_translations  pull_translations \
        push_translations \
        detect_changed_source_translations validate_translations check_keywords \
        dev.pull dev.up dev.down dev.stop dev.makemigrations dev.shell dev.logs \
        dev.restart-container dev.attach \
        app-up app-down app-stop app-makemigrations app-shell app-logs \
        app-restart-container app-attach

define BROWSER_PYSCRIPT
import os, webbrowser, sys
try:
	from urllib import pathname2url
except:
	from urllib.request import pathname2url

webbrowser.open("file://" + pathname2url(os.path.abspath(sys.argv[1])))
endef
export BROWSER_PYSCRIPT
BROWSER := python -c "$$BROWSER_PYSCRIPT"

# Generates a help message. Borrowed from https://github.com/pydanny/cookiecutter-djangopackage.
help: ## display this help message
	@echo "Please use \`make <target>\` where <target> is one of"
	@awk -F ':.*?## ' '/^[a-zA-Z]/ && NF==2 {printf "\033[36m  %-25s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST) | sort

clean: ## delete generated byte code and coverage reports
	find . -name '*.pyc' -delete
	coverage erase
	rm -rf assets
	rm -rf pii_report

piptools: ## install pinned version of pip-compile and pip-sync
	pip install -U 'pip<25.3'
	pip install -r requirements/pip-tools.txt

requirements: piptools dev_requirements ## sync to default requirements

ci_requirements: validation_requirements ## sync to requirements needed for CI checks

dev_requirements: ## sync to requirements for local development
	pip-sync -q requirements/dev.txt

validation_requirements: ## sync to requirements for testing & code quality checking
	pip-sync -q requirements/validation.txt

doc_requirements:
	pip-sync -q requirements/doc.txt

production-requirements: piptools ## install requirements for production
	pip-sync -q requirements/production.txt

static: ## generate static files
	python manage.py collectstatic --noinput

shell: ## run Django shell
	python manage.py shell

test: clean ## run tests and generate coverage report
	pytest --ds=enterprise_access.settings.test

# To be run from CI context
coverage: clean
	pytest --cov-report html
	$(BROWSER) htmlcov/index.html

isort_check: ## check that isort has been run
	isort --check-only enterprise_access/

isort: ## run isort to sort imports in all Python files
	isort --atomic enterprise_access/

style: ## run Python style checker
	pycodestyle enterprise_access manage.py

lint: ## run Python code linting
	pylint --rcfile=pylintrc enterprise_access/ *.py

quality: style isort_check lint ## check code style and import sorting, then lint
	@echo "\e[32mQuality tests passed!\e[0m"

quality_fix: style isort lint ## Check code style, FIX any imports, then lint
	@echo "\e[32mQuality tests passed!\e[0m"

pii_check: ## check for PII annotations on all Django models
	DJANGO_SETTINGS_MODULE=enterprise_access.settings.test \
	code_annotations django_find_annotations --config_file .pii_annotations.yml --lint --report --coverage

check_keywords: ## Scan the Django models in all installed apps in this project for restricted field names
	python manage.py check_reserved_keywords --override_file db_keyword_overrides.yml

validate: test quality pii_check check_keywords ## run tests, quality, and PII annotation checks

migrate: ## apply database migrations
	python manage.py migrate

html_coverage: ## generate and view HTML coverage report
	coverage html && open htmlcov/index.html

COMMON_CONSTRAINTS_TXT=requirements/common_constraints.txt
.PHONY: $(COMMON_CONSTRAINTS_TXT)
$(COMMON_CONSTRAINTS_TXT):
	wget -O "$(@)" https://raw.githubusercontent.com/edx/edx-lint/master/edx_lint/files/common_constraints.txt || touch "$(@)"
	echo "$(COMMON_CONSTRAINTS_TEMP_COMMENT)" | cat - $(@) > temp && mv temp $(@)

upgrade: export CUSTOM_COMPILE_COMMAND=make upgrade
upgrade: piptools $(COMMON_CONSTRAINTS_TXT)  ## update the requirements/*.txt files with the latest packages satisfying requirements/*.in
	sed 's/django-simple-history==3.0.0//g' requirements/common_constraints.txt > requirements/common_constraints.tmp
	mv requirements/common_constraints.tmp requirements/common_constraints.txt
	# Make sure to compile files after any other files they include!
	sed 's/Django<4.0//g' requirements/common_constraints.txt > tmp_con; cat tmp_con > requirements/common_constraints.txt; rm tmp_con
	pip-compile --allow-unsafe --rebuild --upgrade -o requirements/pip.txt requirements/pip.in
	pip-compile --upgrade -o requirements/pip-tools.txt requirements/pip-tools.in
	pip install -qr requirements/pip.txt
	pip install -qr requirements/pip-tools.txt
	pip-compile --upgrade -o requirements/base.txt requirements/base.in
	pip-compile --upgrade -o requirements/test.txt requirements/test.in
	pip-compile --upgrade -o requirements/doc.txt requirements/doc.in
	pip-compile --upgrade -o requirements/quality.txt requirements/quality.in
	pip-compile --upgrade -o requirements/validation.txt requirements/validation.in
	pip-compile --upgrade -o requirements/dev.txt requirements/dev.in
	pip-compile --upgrade -o requirements/production.txt requirements/production.in
	# Let tox control the Django version for tests
	grep -e "^django==" requirements/base.txt > requirements/django.txt
	sed '/^[dD]jango==/d' requirements/test.txt > requirements/test.tmp
	mv requirements/test.tmp requirements/test.txt

extract_translations: ## extract strings to be translated, outputting .mo files
	python manage.py makemessages -l en -v1 -d django
	python manage.py makemessages -l en -v1 -d djangojs

dummy_translations: ## generate dummy translation (.po) files
	cd enterprise_access && i18n_tool dummy

compile_translations: # compile translation files, outputting .po files for each supported language
	python manage.py compilemessages

fake_translations: ## generate and compile dummy translation files

pull_translations: ## pull translations from Transifex
	tx pull -t -a -f --mode reviewed

push_translations: ## push source translation files (.po) from Transifex
	tx push -s

detect_changed_source_translations: ## check if translation files are up-to-date
	cd enterprise_access && i18n_tool changed

validate_translations: fake_translations detect_changed_source_translations ## install fake translations and check if translation files are up-to-date

travis_docker_tag: docker_build
	docker tag openedx/enterprise-access openedx/enterprise-access:$$TRAVIS_COMMIT
	docker tag openedx/enterprise-access:latest-newrelic openedx/enterprise-access:$$TRAVIS_COMMIT-newrelic

travis_docker_auth:
	echo "$$DOCKER_PASSWORD" | docker login -u "$$DOCKER_USERNAME" --password-stdin

travis_docker_push: travis_docker_tag travis_docker_auth ## push to docker hub
	docker push 'openedx/enterprise-access:latest'
	docker push "openedx/enterprise-access:$$TRAVIS_COMMIT"
	docker push 'openedx/enterprise-access:latest-newrelic'
	docker push "openedx/enterprise-access:$$TRAVIS_COMMIT-newrelic"


####################################################################
# Docker shortcuts for managing a local test/quality container.    #
# For full devstack (app, worker, DB, etc.), see the devstack      #
# repository which now manages enterprise-access as a first-class  #
# service.                                                         #
####################################################################

dev.pull: ## Pulls the docker image used by the app container
	docker compose pull

dev.up: dev.pull ## Starts the app container
	docker compose up --remove-orphans -d

dev.down: ## Kills the app container and all its data that isn't in volumes
	docker compose down

dev.stop: ## Stops the app container so it can be restarted
	docker compose stop

dev.makemigrations: ## Create migrations via the app container
	docker compose exec app python manage.py makemigrations

dev.shell: ## Launch a shell in the app container
	docker compose exec app bash

dev.logs: ## View the logs of the app container
	docker compose logs -f --tail=500 app

dev.restart-container: ## Restart the app container
	docker compose restart

dev.attach: ## Attach to the app container
	docker compose attach app

app-up: dev.up
app-down: dev.down
app-stop: dev.stop
app-makemigrations: dev.makemigrations
app-shell: dev.shell
app-logs: dev.logs
app-restart-container: dev.restart-container
app-attach: dev.attach

github_docker_auth:
	echo "$$DOCKERHUB_PASSWORD" | docker login -u "$$DOCKERHUB_USERNAME" --password-stdin

selfcheck: ## check that the Makefile is well-formed
	@echo "The Makefile is well-formed."
