# Generated by Django 5.2.17 on 2026-09-29 01:12

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PathwayPromotedTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Short name for the topic, e.g. "Artificial Intelligence".',
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "subjects",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="JSON list of catalog subject names that put a course in this topic.",
                    ),
                ),
                (
                    "skill_names",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="JSON list of course skill tags that put a course in this topic.",
                    ),
                ),
                (
                    "max_per_pathway",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Most seats one pathway gives this topic, flagships included.",
                    ),
                ),
                (
                    "gate_top_k",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Only the first this-many candidates of a rung, in relevance order, are considered.",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Why this topic is promoted: who decided it, when, and on what evidence."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to switch the topic off. Topics are deactivated, never deleted.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pathway Promoted Topic",
                "verbose_name_plural": "Pathway Promoted Topics",
            },
        ),
        migrations.CreateModel(
            name="HistoricalPathwayCourseRule",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "course_key",
                    models.CharField(
                        db_index=True,
                        help_text='Course key exactly as the catalog spells it, e.g. "HarvardX+CS50P".',
                        max_length=255,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("exclude", "Exclude"), ("flagship", "Flagship")],
                        help_text="exclude: never show this course. flagship: prefer it where it is on topic.",
                        max_length=16,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Introductory", "Introductory"),
                            ("Intermediate", "Intermediate"),
                            ("Advanced", "Advanced"),
                        ],
                        default="",
                        help_text="Flagship only (required there): the rung the course is seated at. Blank for exclude.",
                        max_length=16,
                    ),
                ),
                (
                    "scope_skills",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Flagship only: JSON list of career skill names. The rule applies to a career carrying at least one of them. Empty applies it to every career.",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Why this rule exists: who decided it, when, and on what evidence."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to switch the rule off. Rules are deactivated, never deleted.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Pathway Course Rule",
                "verbose_name_plural": "historical Pathway Course Rules",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPathwayPromotedTopic",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text='Short name for the topic, e.g. "Artificial Intelligence".',
                        max_length=255,
                    ),
                ),
                (
                    "subjects",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="JSON list of catalog subject names that put a course in this topic.",
                    ),
                ),
                (
                    "skill_names",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="JSON list of course skill tags that put a course in this topic.",
                    ),
                ),
                (
                    "max_per_pathway",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Most seats one pathway gives this topic, flagships included.",
                    ),
                ),
                (
                    "gate_top_k",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Only the first this-many candidates of a rung, in relevance order, are considered.",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Why this topic is promoted: who decided it, when, and on what evidence."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to switch the topic off. Topics are deactivated, never deleted.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Pathway Promoted Topic",
                "verbose_name_plural": "historical Pathway Promoted Topics",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="PathwayCourseRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "course_key",
                    models.CharField(
                        db_index=True,
                        help_text='Course key exactly as the catalog spells it, e.g. "HarvardX+CS50P".',
                        max_length=255,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("exclude", "Exclude"), ("flagship", "Flagship")],
                        help_text="exclude: never show this course. flagship: prefer it where it is on topic.",
                        max_length=16,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Introductory", "Introductory"),
                            ("Intermediate", "Intermediate"),
                            ("Advanced", "Advanced"),
                        ],
                        default="",
                        help_text="Flagship only (required there): the rung the course is seated at. Blank for exclude.",
                        max_length=16,
                    ),
                ),
                (
                    "scope_skills",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Flagship only: JSON list of career skill names. The rule applies to a career carrying at least one of them. Empty applies it to every career.",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Why this rule exists: who decided it, when, and on what evidence."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to switch the rule off. Rules are deactivated, never deleted.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pathway Course Rule",
                "verbose_name_plural": "Pathway Course Rules",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("course_key", "action"),
                        name="unique_pathway_course_rule_key_action",
                    )
                ],
            },
        ),
    ]
