# Generated by Django 5.2.17 on 2026-09-29 12:06
"""
Add ``PathwayPromotedTopic.title_terms`` and fill it on the seeded AI topic.

Bench round 1 showed that a skill tag is not evidence that a course is about AI: the
"Artificial Intelligence" tag sits on "Project Management Basics" and on a cloud-native
survey course. From here a course belongs to a topic by subject or by a title term, and
``skill_names`` only keeps the topic's own skills from counting as career overlap.

"Machine Learning" is deliberately not a term, matching the round 1 rule that machine
learning alone does not make a course AI. On the dev careers it was the only term that
seated an off-topic course ("Machine Learning for Semiconductor Quantum Devices" for
Software Engineer).

The data step never overwrites an admin edit: it creates the AI topic only if it is
missing (``get_or_create``, as migration 0002 does), and on an existing row it fills
``title_terms`` only while that list is still empty and rewords ``reason`` only while it
is still 0002's text, which describes the old skill-tag rule. Reversing restores that
text on a row still holding this migration's wording, so 0002's own reverse still
recognises an unedited seeded row; reversing the ``AddField`` drops the terms.
"""
from django.db import migrations, models

TOPIC_NAME = 'Artificial Intelligence'

AI_TITLE_TERMS = [
    'Agentic',
    'AI',
    'AI-Powered',
    'Artificial Intelligence',
    'ChatGPT',
    'Copilot',
    'Gen AI',
    'GenAI',
    'Generative',
    'Large Language',
    'LLM',
    'LLMs',
    'Prompt Engineering',
]

#: The full row, used only when the topic is missing altogether. Values match migration 0002.
AI_TOPIC_DEFAULTS = {
    'subjects': ['Artificial Intelligence'],
    'skill_names': [
        'Artificial Intelligence',
        'ChatGPT',
        'Deep Learning',
        'Generative Artificial Intelligence',
        'Large Language Modeling',
        'Prompt Engineering',
        'Responsible AI',
    ],
    'title_terms': AI_TITLE_TERMS,
    'max_per_pathway': 1,
    'gate_top_k': 10,
    'reason': (
        'Bench round 1, 2026-09-28 (product review of generated pathways): promote at most one AI '
        "course per pathway, and only one about this career's work, never a generic AI course. A "
        'course counts as AI by the subject Artificial Intelligence or a title term (a skill tag '
        'alone does not count, and neither does Machine Learning alone). It is about the career\'s '
        'work when it shares a skill with the career and its title or descriptions name that skill.'
    ),
    'is_active': True,
}

#: Migration 0002's wording, which described the skill-tag rule this migration replaces.
SEEDED_0002_REASON = (
    'Bench round 1, 2026-09-28 (product review of generated pathways): promote at most one AI '
    "course per pathway, and only one about this career's work, never a generic AI course. A "
    'course counts as AI by the subject Artificial Intelligence or one of skill_names; Machine '
    'Learning alone does not count.'
)


def fill_ai_title_terms(apps, schema_editor):
    """
    Create the AI topic if missing. Otherwise fill ``title_terms`` only while it is empty,
    and reword ``reason`` only while it is still migration 0002's text.
    """
    topic_model = apps.get_model('pathway_editorial', 'PathwayPromotedTopic')
    topic, created = topic_model.objects.get_or_create(name=TOPIC_NAME, defaults=AI_TOPIC_DEFAULTS)
    if created:
        return
    changed = []
    if not topic.title_terms:
        topic.title_terms = list(AI_TITLE_TERMS)
        changed.append('title_terms')
    if topic.reason == SEEDED_0002_REASON:
        topic.reason = AI_TOPIC_DEFAULTS['reason']
        changed.append('reason')
    if changed:
        topic.save(update_fields=changed)


def restore_seeded_reason(apps, schema_editor):
    """Put 0002's wording back on a row that still holds this migration's, so 0002 can reverse."""
    topic_model = apps.get_model('pathway_editorial', 'PathwayPromotedTopic')
    topic_model.objects.filter(name=TOPIC_NAME, reason=AI_TOPIC_DEFAULTS['reason']).update(
        reason=SEEDED_0002_REASON,
    )


class Migration(migrations.Migration):
    """Schema and data migration adding title terms to promoted topics."""

    dependencies = [
        ("pathway_editorial", "0002_seed_round1_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpathwaypromotedtopic",
            name="title_terms",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='JSON list of words or phrases that put a course in this topic when its title contains one as whole words, ignoring case, e.g. ["AI", "Generative", "Copilot"].',
            ),
        ),
        migrations.AddField(
            model_name="pathwaypromotedtopic",
            name="title_terms",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='JSON list of words or phrases that put a course in this topic when its title contains one as whole words, ignoring case, e.g. ["AI", "Generative", "Copilot"].',
            ),
        ),
        migrations.AlterField(
            model_name="historicalpathwaypromotedtopic",
            name="skill_names",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="JSON list of the topic's own skill tags. They do not put a course in the topic; they are left out when checking that a course shares a skill with the career.",
            ),
        ),
        migrations.AlterField(
            model_name="pathwaypromotedtopic",
            name="skill_names",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="JSON list of the topic's own skill tags. They do not put a course in the topic; they are left out when checking that a course shares a skill with the career.",
            ),
        ),
        migrations.RunPython(fill_ai_title_terms, restore_seeded_reason),
    ]
