# Generated by Django 5.2.12 on 2026-06-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidy_access_policy', '0030_mariadb_uuid_conversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubsidyaccesspolicy',
            name='active',
            field=models.BooleanField(default=False, help_text='Set to FALSE to deactivate this policy, and hide it from both admins and learners. Use this when you want to effectively soft-delete this policy. A typical use case is that the policy was created on accident or as a test. Caveat: you cannot deactivate a policy with existing spend/enrollments.'),
        ),
        migrations.AlterField(
            model_name='historicalsubsidyaccesspolicy',
            name='retired',
            field=models.BooleanField(default=False, help_text="Set to TRUE to deactivate this policy, but NOT hide it from admins. Use this when you want to disable redemption, but you can't set active=False because this policy already has spend/enrollments."),
        ),
        migrations.AlterField(
            model_name='subsidyaccesspolicy',
            name='active',
            field=models.BooleanField(default=False, help_text='Set to FALSE to deactivate this policy, and hide it from both admins and learners. Use this when you want to effectively soft-delete this policy. A typical use case is that the policy was created on accident or as a test. Caveat: you cannot deactivate a policy with existing spend/enrollments.'),
        ),
        migrations.AlterField(
            model_name='subsidyaccesspolicy',
            name='retired',
            field=models.BooleanField(default=False, help_text="Set to TRUE to deactivate this policy, but NOT hide it from admins. Use this when you want to disable redemption, but you can't set active=False because this policy already has spend/enrollments."),
        ),
    ]
