# Generated by Django 5.2.17 on 2026-10-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0007_associateacademystep'),
    ]

    operations = [
        migrations.AddField(
            model_name='associateacademystep',
            name='call_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='getcreatecatalogstep',
            name='call_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='getcreatecustomeragreementstep',
            name='call_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='getcreatecustomerstep',
            name='call_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='getcreateenterpriseadminusersstep',
            name='call_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='getcreatefirstpaidsubscriptionplanstep',
            name='call_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='getcreatesubscriptionplanrenewalstep',
            name='call_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='getcreatetrialsubscriptionplanstep',
            name='call_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationstep',
            name='call_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provisionnewcustomerworkflow',
            name='call_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
