# Generated by Django 5.2.17 on 2026-10-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsquaredworkflowstep',
            name='call_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testtwostepworkflow',
            name='call_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testworkflow',
            name='call_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testworkflowstep',
            name='call_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
