# Generated by Django 4.2.25 on 2025-11-04 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_billing', '0017_summary_renewal_and_future_plan_uuids'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCheckoutIntentRenewal',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('subscription_plan_renewal_id', models.UUIDField(help_text='UUID of the SubscriptionPlanRenewal in License Manager')),
                ('stripe_subscription_id', models.CharField(db_index=True, help_text='The Stripe subscription ID for this renewal', max_length=255)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the renewal was successfully processed in License Manager', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('checkout_intent', models.ForeignKey(blank=True, db_constraint=False, help_text='The CheckoutIntent this renewal is associated with', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customer_billing.checkoutintent')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stripe_event_data', models.ForeignKey(blank=True, db_constraint=False, help_text='The Stripe event that triggered this renewal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customer_billing.stripeeventdata')),
            ],
            options={
                'verbose_name': 'historical Checkout Intent Renewal',
                'verbose_name_plural': 'historical Checkout Intent Renewals',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CheckoutIntentRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('subscription_plan_renewal_id', models.UUIDField(help_text='UUID of the SubscriptionPlanRenewal in License Manager')),
                ('stripe_subscription_id', models.CharField(db_index=True, help_text='The Stripe subscription ID for this renewal', max_length=255)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the renewal was successfully processed in License Manager', null=True)),
                ('checkout_intent', models.ForeignKey(help_text='The CheckoutIntent this renewal is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='customer_billing.checkoutintent')),
                ('stripe_event_data', models.OneToOneField(help_text='The Stripe event that triggered this renewal', on_delete=django.db.models.deletion.CASCADE, related_name='renewal_processing', to='customer_billing.stripeeventdata')),
            ],
            options={
                'verbose_name': 'Checkout Intent Renewal',
                'verbose_name_plural': 'Checkout Intent Renewals',
                'ordering': ['-created'],
            },
        ),
    ]
