# Generated by Django 5.2.9 on 2026-03-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0026_add_subscription_cancel_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfservicesubscriptionrenewal',
            name='stripe_invoice_id',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='The Stripe invoice ID that this renewal corresponds to.',
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='selfservicesubscriptionrenewal',
            name='effective_date',
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text=(
                    'The datetime at which this renewal is expected to take effect, '
                    'derived from the period end of the previous subscription cycle. '
                    'This is a local cache of the like-named column on the '
                    'license-manager SubscriptionPlanRenewal model.'
                ),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='historicalselfservicesubscriptionrenewal',
            name='stripe_invoice_id',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='The Stripe invoice ID that this renewal corresponds to.',
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='historicalselfservicesubscriptionrenewal',
            name='effective_date',
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text=(
                    'The datetime at which this renewal is expected to take effect, '
                    'derived from the period end of the previous subscription cycle. '
                    'This is a local cache of the like-named column on the '
                    'license-manager SubscriptionPlanRenewal model.'
                ),
                null=True,
            ),
        ),
    ]
