# Generated by Django 5.2.11 on 2026-03-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0026_add_subscription_cancel_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalselfservicesubscriptionrenewal',
            name='is_canceled',
            field=models.BooleanField(db_index=True, default=False, help_text='True if the subscription has been canceled. Can be set back to False if subscription is un-canceled.'),
        ),
        migrations.AddField(
            model_name='selfservicesubscriptionrenewal',
            name='is_canceled',
            field=models.BooleanField(db_index=True, default=False, help_text='True if the subscription has been canceled. Can be set back to False if subscription is un-canceled.'),
        ),
    ]
