# Generated by Django 5.2.11 on 2026-03-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0028_backfill_renewal_invoice_and_effective_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalselfservicesubscriptionrenewal',
            name='is_canceled',
            field=models.BooleanField(db_index=True, default=False, help_text='True if the subscription has been canceled. Can be set back to False if subscription is un-canceled.'),
        ),
        migrations.AddField(
            model_name='selfservicesubscriptionrenewal',
            name='is_canceled',
            field=models.BooleanField(db_index=True, default=False, help_text='True if the subscription has been canceled. Can be set back to False if subscription is un-canceled.'),
        ),
    ]
