# Generated by Django 5.2.9 on 2026-04-12 14:36

import django.db.models.deletion
import django_extensions.db.fields
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_billing", "0030_backfill_subscription_renewal_cancellations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EnterpriseAcademy",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this Academy record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Short identifier name for the Academy.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "long_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Full public name of the Academy.",
                        max_length=512,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Marketing summary of the Academy.",
                    ),
                ),
                (
                    "marketing_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Public-facing marketing URL for the Academy.",
                        max_length=2048,
                    ),
                ),
                (
                    "thumbnail_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Stored thumbnail path or URL for the Academy image.",
                        max_length=2048,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of competency tags associated with the Academy.",
                    ),
                ),
                (
                    "stripe_product_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Stripe Product ID associated with the Academy.",
                        max_length=255,
                    ),
                ),
                (
                    "stripe_price_lookup_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Stripe price lookup key used to resolve academy pricing context.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "enterprise_catalog_uuid",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Related edX catalog UUID.",
                        null=True,
                    ),
                ),
                (
                    "product_key",
                    models.SlugField(
                        blank=True,
                        default="",
                        help_text="Routing key that maps to ?product_key= checkout entry parameter.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        default="",
                        help_text="Stable URL-safe slug for academy routes.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Controls whether this academy is active for API consumers.",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Ascending list sort order for academy responses.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academy",
                "verbose_name_plural": "Academies",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalEnterpriseAcademy",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this Academy record.",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Short identifier name for the Academy.",
                        max_length=255,
                    ),
                ),
                (
                    "long_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Full public name of the Academy.",
                        max_length=512,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Marketing summary of the Academy.",
                    ),
                ),
                (
                    "marketing_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Public-facing marketing URL for the Academy.",
                        max_length=2048,
                    ),
                ),
                (
                    "thumbnail_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Stored thumbnail path or URL for the Academy image.",
                        max_length=2048,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of competency tags associated with the Academy.",
                    ),
                ),
                (
                    "stripe_product_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Stripe Product ID associated with the Academy.",
                        max_length=255,
                    ),
                ),
                (
                    "stripe_price_lookup_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Stripe price lookup key used to resolve academy pricing context.",
                        max_length=255,
                    ),
                ),
                (
                    "enterprise_catalog_uuid",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Related edX catalog UUID.",
                        null=True,
                    ),
                ),
                (
                    "product_key",
                    models.SlugField(
                        blank=True,
                        default="",
                        help_text="Routing key that maps to ?product_key= checkout entry parameter.",
                        max_length=255,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        default="",
                        help_text="Stable URL-safe slug for academy routes.",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Controls whether this academy is active for API consumers.",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Ascending list sort order for academy responses.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Academy",
                "verbose_name_plural": "historical Academies",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
