# Generated by Django 5.2.13 on 2026-05-21 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_billing", "0031_enterpriseacademy_historicalenterpriseacademy"),
        ("provisioning", "0006_getcreatefirstpaidsubscriptionplanstep_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Rename enterprise_catalog_uuid -> catalog_query_id (preserves data)
        migrations.RenameField(
            model_name="enterpriseacademy",
            old_name="enterprise_catalog_uuid",
            new_name="catalog_query_id",
        ),
        migrations.RenameField(
            model_name="historicalenterpriseacademy",
            old_name="enterprise_catalog_uuid",
            new_name="catalog_query_id",
        ),
        # Update help_text on renamed field
        migrations.AlterField(
            model_name="enterpriseacademy",
            name="catalog_query_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Catalog query UUID for this Academy.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalenterpriseacademy",
            name="catalog_query_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Catalog query UUID for this Academy.",
                null=True,
            ),
        ),
        # Add stripe_product_id to CheckoutIntent
        migrations.AddField(
            model_name="checkoutintent",
            name="stripe_product_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Stripe Product ID for paid/academy intents. NULL for Teams intents.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcheckoutintent",
            name="stripe_product_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Stripe Product ID for paid/academy intents. NULL for Teams intents.",
                max_length=255,
                null=True,
            ),
        ),
        # Change CheckoutIntent.user from OneToOneField to ForeignKey
        migrations.AlterField(
            model_name="checkoutintent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="historicalcheckoutintent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # Add partial unique constraints (scoped to active states only)
        migrations.AddConstraint(
            model_name="checkoutintent",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("state__in", ["created", "paid"]),
                    ("stripe_product_id__isnull", False),
                ),
                fields=("user", "enterprise_slug", "stripe_product_id"),
                name="unique_active_checkout_intent_with_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="checkoutintent",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("state__in", ["created", "paid"]),
                    ("stripe_product_id__isnull", True),
                ),
                fields=("user", "enterprise_slug"),
                name="unique_active_checkout_intent_without_product",
            ),
        ),
    ]
