# Generated by Django 5.2.13 on 2026-05-28 15:25

import django.db.models.deletion
import django_extensions.db.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0031_enterpriseacademy_historicalenterpriseacademy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SspProduct',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('slug', models.SlugField(help_text='Universal cross-service identifier, e.g. "teams-yearly", "ai-academy-yearly".', max_length=255, primary_key=True, serialize=False)),
                ('stripe_price_lookup_key', models.CharField(help_text='Stripe Price lookup_key for this product.', max_length=255, unique=True)),
                ('academy_uuid', models.UUIDField(blank=True, db_index=True, help_text='enterprise-catalog Academy UUID. Null for non-Academy products (e.g. Teams).', null=True)),
                ('catalog_query_uuid', models.UUIDField(help_text='enterprise-catalog CatalogQuery UUID used for provisioning.')),
                ('license_manager_product_id_trial', models.IntegerField(blank=True, help_text='license-manager product ID for the trial subscription period.', null=True)),
                ('license_manager_product_id_paid', models.IntegerField(blank=True, help_text='license-manager product ID for the paid subscription period.', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'SSP Product',
                'verbose_name_plural': 'SSP Products',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSspProduct',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('slug', models.SlugField(help_text='Universal cross-service identifier, e.g. "teams-yearly", "ai-academy-yearly".', max_length=255)),
                ('stripe_price_lookup_key', models.CharField(db_index=True, help_text='Stripe Price lookup_key for this product.', max_length=255)),
                ('academy_uuid', models.UUIDField(blank=True, db_index=True, help_text='enterprise-catalog Academy UUID. Null for non-Academy products (e.g. Teams).', null=True)),
                ('catalog_query_uuid', models.UUIDField(help_text='enterprise-catalog CatalogQuery UUID used for provisioning.')),
                ('license_manager_product_id_trial', models.IntegerField(blank=True, help_text='license-manager product ID for the trial subscription period.', null=True)),
                ('license_manager_product_id_paid', models.IntegerField(blank=True, help_text='license-manager product ID for the paid subscription period.', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical SSP Product',
                'verbose_name_plural': 'historical SSP Products',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
