# Generated by Django 5.2.13 on 2026-05-21 15:26

import django.db.models.deletion
import enterprise_access.apps.customer_billing.constants
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_billing", "0031_enterpriseacademy_historicalenterpriseacademy"),
        ("provisioning", "0006_getcreatefirstpaidsubscriptionplanstep_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enterpriseacademy",
            name="enterprise_catalog_uuid",
        ),
        migrations.RemoveField(
            model_name="historicalenterpriseacademy",
            name="enterprise_catalog_uuid",
        ),
        migrations.AddField(
            model_name="checkoutintent",
            name="stripe_product_id",
            field=models.CharField(
                db_index=True,
                help_text="Stripe Product ID for Academy-based checkout intents; NULL for Teams intents",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="enterpriseacademy",
            name="catalog_query_id",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="Related edX catalog query ID.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcheckoutintent",
            name="stripe_product_id",
            field=models.CharField(
                db_index=True,
                help_text="Stripe Product ID for Academy-based checkout intents; NULL for Teams intents",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalenterpriseacademy",
            name="catalog_query_id",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="Related edX catalog query ID.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="checkoutintent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkout_intents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="checkoutintent",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("stripe_product_id__isnull", False),
                    (
                        "state__in",
                        [
                            enterprise_access.apps.customer_billing.constants.CheckoutIntentState[
                                "CREATED"
                            ],
                            enterprise_access.apps.customer_billing.constants.CheckoutIntentState[
                                "PAID"
                            ],
                            enterprise_access.apps.customer_billing.constants.CheckoutIntentState[
                                "FULFILLED"
                            ],
                            enterprise_access.apps.customer_billing.constants.CheckoutIntentState[
                                "ERRORED_BACKOFFICE"
                            ],
                            enterprise_access.apps.customer_billing.constants.CheckoutIntentState[
                                "ERRORED_FULFILLMENT_STALLED"
                            ],
                            enterprise_access.apps.customer_billing.constants.CheckoutIntentState[
                                "ERRORED_PROVISIONING"
                            ],
                        ],
                    ),
                ),
                fields=("user", "enterprise_slug", "stripe_product_id"),
                name="unique_academy_intent_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="checkoutintent",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("stripe_product_id__isnull", True),
                    (
                        "state__in",
                        [
                            enterprise_access.apps.customer_billing.constants.CheckoutIntentState[
                                "CREATED"
                            ],
                            enterprise_access.apps.customer_billing.constants.CheckoutIntentState[
                                "PAID"
                            ],
                            enterprise_access.apps.customer_billing.constants.CheckoutIntentState[
                                "FULFILLED"
                            ],
                            enterprise_access.apps.customer_billing.constants.CheckoutIntentState[
                                "ERRORED_BACKOFFICE"
                            ],
                            enterprise_access.apps.customer_billing.constants.CheckoutIntentState[
                                "ERRORED_FULFILLMENT_STALLED"
                            ],
                            enterprise_access.apps.customer_billing.constants.CheckoutIntentState[
                                "ERRORED_PROVISIONING"
                            ],
                        ],
                    ),
                ),
                fields=("user", "enterprise_slug"),
                name="unique_teams_intent_per_user",
            ),
        ),
    ]
