# Generated by Django 5.2.13 on 2026-06-03 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0033_seed_teams_yearly_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnterpriseAcademy',
        ),
        migrations.DeleteModel(
            name='HistoricalEnterpriseAcademy',
        ),
    ]
