# Generated by Django 5.2.13 on 2026-06-01 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0034_drop_ent_academy_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutintent',
            name='ssp_product',
            field=models.ForeignKey(blank=True, help_text='The SSP product associated with this checkout intent.', null=True, on_delete=django.db.models.deletion.PROTECT, to='customer_billing.sspproduct'),
        ),
        migrations.AddField(
            model_name='historicalcheckoutintent',
            name='ssp_product',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The SSP product associated with this checkout intent.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customer_billing.sspproduct'),
        ),
    ]
