# Generated by Django 5.2.13 on 2026-07-09 13:59

import django.db.models.deletion
import enterprise_access.apps.customer_billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0038_sspproduct_marketing_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsspproduct',
            name='catalog_query_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='The enterprise-catalog CatalogQuery.id value, used during provisioning.', null=True),
        ),
        migrations.AddField(
            model_name='sspproduct',
            name='catalog_query_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='The enterprise-catalog CatalogQuery.id value, used during provisioning.', null=True),
        ),
    ]
