# Generated by Django 5.2.13 on 2026-07-09 16:41

import django.db.models.deletion
import enterprise_access.apps.customer_billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0039_add_ssp_product_cat_query_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutintent',
            name='ssp_product',
            field=models.ForeignKey(default=enterprise_access.apps.customer_billing.models.get_default_ssp_product_slug, help_text='The SSP product associated with this checkout intent.', on_delete=django.db.models.deletion.PROTECT, to='customer_billing.sspproduct'),
        ),
        migrations.AlterField(
            model_name='historicalcheckoutintent',
            name='ssp_product',
            field=models.ForeignKey(blank=True, db_constraint=False, default=enterprise_access.apps.customer_billing.models.get_default_ssp_product_slug, help_text='The SSP product associated with this checkout intent.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customer_billing.sspproduct'),
        ),
    ]
