# Generated by Django 5.2.15 on 2026-07-13 14:39

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0040_alter_checkoutintent_ssp_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutintent',
            name='billing_address_city',
            field=models.CharField(blank=True, help_text='Billing address city.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='checkoutintent',
            name='billing_address_country',
            field=django_countries.fields.CountryField(blank=True, help_text='Two-letter ISO country code for the billing address.', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='checkoutintent',
            name='billing_address_line_1',
            field=models.CharField(blank=True, help_text='First line of the billing street address.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='checkoutintent',
            name='billing_address_line_2',
            field=models.CharField(blank=True, help_text='Second line of the billing street address.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='checkoutintent',
            name='billing_address_postal_code',
            field=models.CharField(blank=True, help_text='Billing address postal code.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='checkoutintent',
            name='billing_address_state',
            field=models.CharField(blank=True, help_text='Billing address state or province.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcheckoutintent',
            name='billing_address_city',
            field=models.CharField(blank=True, help_text='Billing address city.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcheckoutintent',
            name='billing_address_country',
            field=django_countries.fields.CountryField(blank=True, help_text='Two-letter ISO country code for the billing address.', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='historicalcheckoutintent',
            name='billing_address_line_1',
            field=models.CharField(blank=True, help_text='First line of the billing street address.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcheckoutintent',
            name='billing_address_line_2',
            field=models.CharField(blank=True, help_text='Second line of the billing street address.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcheckoutintent',
            name='billing_address_postal_code',
            field=models.CharField(blank=True, help_text='Billing address postal code.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalcheckoutintent',
            name='billing_address_state',
            field=models.CharField(blank=True, help_text='Billing address state or province.', max_length=255, null=True),
        ),
    ]
