# Generated by Django 5.2.13 on 2026-07-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_billing', '0040_alter_checkoutintent_ssp_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsspproduct',
            name='catalog_query_id',
            field=models.IntegerField(db_index=True, default=0, help_text='The enterprise-catalog CatalogQuery.id value, used during provisioning.'),
        ),
        migrations.AlterField(
            model_name='sspproduct',
            name='catalog_query_id',
            field=models.IntegerField(db_index=True, default=0, help_text='The enterprise-catalog CatalogQuery.id value, used during provisioning.'),
        ),
    ]
