# Generated by Django 5.2.17 on 2026-10-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "customer_billing",
            "0041_alter_historicalsspproduct_catalog_query_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutintent",
            name="attribution",
            field=models.JSONField(
                blank=True,
                help_text="Marketing attribution for the checkout session: utm_source, utm_medium, utm_campaign, utm_content, utm_term, referrer.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcheckoutintent",
            name="attribution",
            field=models.JSONField(
                blank=True,
                help_text="Marketing attribution for the checkout session: utm_source, utm_medium, utm_campaign, utm_content, utm_term, referrer.",
                null=True,
            ),
        ),
    ]
