# Generated by Django 5.2.13 on 2026-07-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "content_assignments",
            "0025_historicallearnercontentassignment_admin_lms_user_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallearnercontentassignmentaction",
            name="actor_lms_user_id",
            field=models.IntegerField(
                blank=True,
                help_text="LMS user ID of the actor who triggered this action.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicallearnercontentassignmentaction",
            name="actor_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin"),
                    ("learner", "Learner"),
                    ("system", "System"),
                ],
                help_text="Type of actor who triggered this action (admin, learner, or system).",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicallearnercontentassignmentaction",
            name="enterprise_customer_uuid",
            field=models.UUIDField(
                blank=True,
                help_text="UUID of the enterprise customer associated with this action.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicallearnercontentassignmentaction",
            name="learner_email",
            field=models.CharField(
                blank=True,
                help_text="Email of the learner affected by this action at the time of the action.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicallearnercontentassignmentaction",
            name="learner_external_key",
            field=models.CharField(
                blank=True,
                help_text="External key of the learner affected by this action, if available.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicallearnercontentassignmentaction",
            name="learner_lms_user_id",
            field=models.IntegerField(
                blank=True,
                help_text="LMS user ID of the learner affected by this action.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicallearnercontentassignmentaction",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Arbitrary audit metadata. Supported keys: correlation_id, batch_id, request_id, state_before, state_after, error_code, error_message, idempotency_key.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicallearnercontentassignmentaction",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin_ui_single", "Admin UI - single assignment"),
                    ("admin_ui_bulk_csv", "Admin UI - bulk CSV upload"),
                    ("browse_request_approve", "Browse and request - single approve"),
                    ("browse_request_approve_all", "Browse and request - approve all"),
                    ("django_admin", "Django admin"),
                    ("api", "API"),
                    ("signal", "Django signal"),
                    ("scheduled_job", "Scheduled job"),
                    ("celery_task", "Celery task"),
                ],
                help_text="Originating source or channel that triggered this action.",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="learnercontentassignmentaction",
            name="actor_lms_user_id",
            field=models.IntegerField(
                blank=True,
                help_text="LMS user ID of the actor who triggered this action.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="learnercontentassignmentaction",
            name="actor_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin"),
                    ("learner", "Learner"),
                    ("system", "System"),
                ],
                help_text="Type of actor who triggered this action (admin, learner, or system).",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="learnercontentassignmentaction",
            name="enterprise_customer_uuid",
            field=models.UUIDField(
                blank=True,
                help_text="UUID of the enterprise customer associated with this action.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="learnercontentassignmentaction",
            name="learner_email",
            field=models.CharField(
                blank=True,
                help_text="Email of the learner affected by this action at the time of the action.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="learnercontentassignmentaction",
            name="learner_external_key",
            field=models.CharField(
                blank=True,
                help_text="External key of the learner affected by this action, if available.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="learnercontentassignmentaction",
            name="learner_lms_user_id",
            field=models.IntegerField(
                blank=True,
                help_text="LMS user ID of the learner affected by this action.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="learnercontentassignmentaction",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Arbitrary audit metadata. Supported keys: correlation_id, batch_id, request_id, state_before, state_after, error_code, error_message, idempotency_key.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="learnercontentassignmentaction",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin_ui_single", "Admin UI - single assignment"),
                    ("admin_ui_bulk_csv", "Admin UI - bulk CSV upload"),
                    ("browse_request_approve", "Browse and request - single approve"),
                    ("browse_request_approve_all", "Browse and request - approve all"),
                    ("django_admin", "Django admin"),
                    ("api", "API"),
                    ("signal", "Django signal"),
                    ("scheduled_job", "Scheduled job"),
                    ("celery_task", "Celery task"),
                ],
                help_text="Originating source or channel that triggered this action.",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicallearnercontentassignmentaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("learner_linked", "Learner linked to customer"),
                    ("notified", "Learner notified of assignment"),
                    ("reminded", "Learner reminded about assignment"),
                    ("redeemed", "Learner redeemed the assigned content"),
                    ("cancelled", "Learner assignment cancelled"),
                    (
                        "cancelled_acknowledged",
                        "Learner assignment cancellation acknowledged by learner",
                    ),
                    ("expired", "Learner assignment expired"),
                    (
                        "expired_acknowledged",
                        "Learner assignment expiration acknowledged by learner",
                    ),
                    ("reversed", "Transaction for this assignment has been reversed"),
                    ("allocated", "Content allocated to learner"),
                    ("reallocated", "Content reallocated to learner"),
                    ("approved", "Assignment approved"),
                    ("errored", "Assignment encountered an error"),
                ],
                db_index=True,
                help_text="The type of action take on the related assignment record.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="learnercontentassignmentaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("learner_linked", "Learner linked to customer"),
                    ("notified", "Learner notified of assignment"),
                    ("reminded", "Learner reminded about assignment"),
                    ("redeemed", "Learner redeemed the assigned content"),
                    ("cancelled", "Learner assignment cancelled"),
                    (
                        "cancelled_acknowledged",
                        "Learner assignment cancellation acknowledged by learner",
                    ),
                    ("expired", "Learner assignment expired"),
                    (
                        "expired_acknowledged",
                        "Learner assignment expiration acknowledged by learner",
                    ),
                    ("reversed", "Transaction for this assignment has been reversed"),
                    ("allocated", "Content allocated to learner"),
                    ("reallocated", "Content reallocated to learner"),
                    ("approved", "Assignment approved"),
                    ("errored", "Assignment encountered an error"),
                ],
                db_index=True,
                help_text="The type of action take on the related assignment record.",
                max_length=255,
            ),
        ),
        migrations.AddIndex(
            model_name="learnercontentassignmentaction",
            index=models.Index(
                fields=["assignment", "created"], name="lcaa_assignment_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="learnercontentassignmentaction",
            index=models.Index(
                fields=["enterprise_customer_uuid", "created"],
                name="lcaa_customer_created_idx",
            ),
        ),
    ]
