# Generated by Django 5.2.17 on 2026-08-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_assignments', '0027_alter_historicallearnercontentassignmentaction_action_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallearnercontentassignmentaction',
            name='action_type',
            field=models.CharField(choices=[('learner_linked', 'Learner linked to customer'), ('notified', 'Learner notified of assignment'), ('reminded', 'Learner reminded about assignment'), ('redeemed', 'Learner redeemed the assigned content'), ('cancelled', 'Learner assignment cancelled'), ('cancelled_acknowledged', 'Learner assignment cancellation acknowledged by learner'), ('cancel_email_failed', 'Learner assignment cancellation email failed to send'), ('auto_expired', 'Assignment automatically transitioned to the expired state'), ('expired', 'Expiration email successfully sent to learner'), ('expired_acknowledged', 'Learner assignment expiration acknowledged by learner'), ('reversed', 'Transaction for this assignment has been reversed'), ('allocated', 'Content allocated to learner'), ('reallocated', 'Content reallocated to learner'), ('approved', 'Assignment approved'), ('errored', 'Assignment encountered an error'), ('retired', 'Learner PII retired/cleared from system')], db_index=True, help_text='The type of action take on the related assignment record.', max_length=255),
        ),
        migrations.AlterField(
            model_name='learnercontentassignmentaction',
            name='action_type',
            field=models.CharField(choices=[('learner_linked', 'Learner linked to customer'), ('notified', 'Learner notified of assignment'), ('reminded', 'Learner reminded about assignment'), ('redeemed', 'Learner redeemed the assigned content'), ('cancelled', 'Learner assignment cancelled'), ('cancelled_acknowledged', 'Learner assignment cancellation acknowledged by learner'), ('cancel_email_failed', 'Learner assignment cancellation email failed to send'), ('auto_expired', 'Assignment automatically transitioned to the expired state'), ('expired', 'Expiration email successfully sent to learner'), ('expired_acknowledged', 'Learner assignment expiration acknowledged by learner'), ('reversed', 'Transaction for this assignment has been reversed'), ('allocated', 'Content allocated to learner'), ('reallocated', 'Content reallocated to learner'), ('approved', 'Assignment approved'), ('errored', 'Assignment encountered an error'), ('retired', 'Learner PII retired/cleared from system')], db_index=True, help_text='The type of action take on the related assignment record.', max_length=255),
        ),
    ]
