# Generated by Django 5.2.12 on 2026-05-19 15:19

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalXpertLearnerPathwaysSystemPrompt',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('notes', models.TextField(blank=True, help_text='Free-form internal notes about this prompt configuration.', null=True)),
                ('system_prompt', models.TextField(help_text='Raw system prompt text sent to Xpert.')),
                ('output_schema', models.JSONField(blank=True, help_text='Optional output schema appended to the system prompt at runtime.', null=True)),
                ('prompt_type', models.CharField(choices=[('learner_intent', 'Learner Intent'), ('recommendations_feedback', 'Recommendations Feedback')], max_length=64)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Xpert Learner Pathways System Prompt',
                'verbose_name_plural': 'historical Xpert Learner Pathways System Prompts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='XpertLearnerPathwaysSystemPrompt',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, help_text='Free-form internal notes about this prompt configuration.', null=True)),
                ('system_prompt', models.TextField(help_text='Raw system prompt text sent to Xpert.')),
                ('output_schema', models.JSONField(blank=True, help_text='Optional output schema appended to the system prompt at runtime.', null=True)),
                ('prompt_type', models.CharField(choices=[('learner_intent', 'Learner Intent'), ('recommendations_feedback', 'Recommendations Feedback')], max_length=64)),
            ],
            options={
                'verbose_name': 'Xpert Learner Pathways System Prompt',
                'verbose_name_plural': 'Xpert Learner Pathways System Prompts',
                'constraints': [models.UniqueConstraint(fields=('prompt_type',), name='unique_xpert_learner_pathways_prompt_type')],
            },
        ),
    ]
