# Generated by Django 5.2.17 on 2026-09-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalxpertlearnerpathwayssystemprompt',
            name='prompt_type',
            field=models.CharField(choices=[('learner_intent', 'Learner Intent'), ('recommendations_feedback', 'Recommendations Feedback'), ('candidate_rerank', 'Candidate Re-rank')], max_length=64),
        ),
        migrations.AlterField(
            model_name='xpertlearnerpathwayssystemprompt',
            name='prompt_type',
            field=models.CharField(choices=[('learner_intent', 'Learner Intent'), ('recommendations_feedback', 'Recommendations Feedback'), ('candidate_rerank', 'Candidate Re-rank')], max_length=64),
        ),
    ]
