""" Generated by Django 5.2.10 on 2026-02-09 05:25 """

import uuid
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):
    """Initial migration for testimonials """
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quote_text", models.TextField()),
                ("attribution_name", models.CharField(max_length=255)),
                ("attribution_title", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="testimonial_is_acti_6bc8bb_idx"
                    )
                ],
            },
        ),
    ]
